l_korean:
 us_custom_weight:0 "lbs"
 metric_weight:0 "kg"

 metric_height:0 "cm"

 metric_length:0 "cm"

 aaa_cups:0 "AAA"
 aa_cups:0 "AA"
 a_cups:0 "A"
 b_cups:0 "B"
 c_cups:0 "C"
 d_cups:0 "D"
 dd_cups:0 "DD"
 ddd_cups:0 "DDD"
 g_cups:0 "G"
 h_cups:0 "H"
 i_cups:0 "I"
 j_cups:0 "J"
 k_cups:0 "K"
 l_cups:0 "L"
 m_cups:0 "M"
 n_cups:0 "N"
 o_cups:0 "O"
 p_cups:0 "P"
 q_cups:0 "Q"
 r_cups:0 "R"
 s_cups:0 "S"
 t_cups:0 "T"
 u_cups:0 "U"
 v_cups:0 "V"
 vv_cups:0 "VV"
 x_cups:0 "X"
 xx_cups:0 "XX"
 xxx_cups:0 "XXX"
 y_cups:0 "Y"
 yy_cups:0 "YY"
 z_cups:0 "Z"
 zz_cups:0 "ZZ"
 why_cups:0 "???"

 two_inches:0 "2""
 three_inches:0 "3""
 four_inches:0 "4""
 five_inches:0 "5""
 six_inches:0 "6""
 seven_inches:0 "7""
 eight_inches:0 "8""
 nine_inches:0 "9""
 ten_inches:0 "10""
 eleven_inches:0 "11""
 twelve_inches:0 "12""
 thirteen_inches:0 "13""
 fourteen_inches:0 "14""
 fifteen_inches:0 "15""
 sixteen_inches:0 "16""
 seventeen_inches:0 "17""
 eighteen_inches:0 "18""
 nineteen_inches:0 "19""
 twenty_inches:0 "20""

 one_foot_eight:0 "1'8""
 one_foot_nine:0 "1'9""
 one_foot_ten:0 "1'10""
 one_foot_eleven:0 "1'11""
 two_foot:0 "2'0""
 two_foot_one:0 "2'1""
 two_foot_two:0 "2'2""
 two_foot_three:0 "2'3""
 two_foot_four:0 "2'4""
 two_foot_five:0 "2'5""
 two_foot_six:0 "2'6""
 two_foot_seven:0 "2'7""
 two_foot_eight:0 "2'8""
 two_foot_nine:0 "2'9""
 two_foot_ten:0 "2'10""
 two_foot_eleven:0 "2'11""
 three_foot:0 "3'0""
 three_foot_one:0 "3'1""
 three_foot_two:0 "3'2""
 three_foot_three:0 "3'3""
 three_foot_four:0 "3'4""
 three_foot_five:0 "3'5""
 three_foot_six:0 "3'6""
 three_foot_seven:0 "3'7""
 three_foot_eight:0 "3'8""
 three_foot_nine:0 "3'9""
 three_foot_ten:0 "3'10""
 three_foot_eleven:0 "3'11""
 four_foot:0 "4'0""
 four_foot_one:0 "4'1""
 four_foot_two:0 "4'2""
 four_foot_three:0 "4'3""
 four_foot_four:0 "4'4""
 four_foot_five:0 "4'5""
 four_foot_six:0 "4'6""
 four_foot_seven:0 "4'7""
 four_foot_eight:0 "4'8""
 four_foot_nine:0 "4'9""
 four_foot_ten:0 "4'10""
 four_foot_eleven:0 "4'11""
 five_foot:0 "5'0""
 five_foot_one:0 "5'1""
 five_foot_two:0 "5'2""
 five_foot_three:0 "5'3""
 five_foot_four:0 "5'4""
 five_foot_five:0 "5'5""
 five_foot_six:0 "5'6""
 five_foot_seven:0 "5'7""
 five_foot_eight:0 "5'8""
 five_foot_nine:0 "5'9""
 five_foot_ten:0 "5'10""
 five_foot_eleven:0 "5'11""
 six_foot:0 "6'0""
 six_foot_one:0 "6'1""
 six_foot_two:0 "6'2""
 six_foot_three:0 "6'3""
 six_foot_four:0 "6'4""
 six_foot_five:0 "6'5""
 six_foot_six:0 "6'6""
 six_foot_seven:0 "6'7""
 six_foot_eight:0 "6'8""
 six_foot_nine:0 "6'9""
 six_foot_ten:0 "6'10""
 six_foot_eleven:0 "6'11""
 seven_foot:0 "7'0""
 seven_foot_one:0 "7'1""
 seven_foot_two:0 "7'2""
 seven_foot_three:0 "7'3""
 seven_foot_four:0 "7'4""
 seven_foot_five:0 "7'5""
 seven_foot_six:0 "7'6""

 24_band:0 "24"
 26_band:0 "26"
 28_band:0 "28"
 30_band:0 "30"
 32_band:0 "32"
 34_band:0 "34"
 36_band:0 "36"
 38_band:0 "38"
 40_band:0 "40"
 42_band:0 "42"
 44_band:0 "44"
 46_band:0 "46"
 48_band:0 "48"
 50_band:0 "50"
 52_band:0 "52"
 54_band:0 "54"
 56_band:0 "56"
 58_band:0 "58"
 60_band:0 "60"
 62_band:0 "62"
 64_band:0 "64"
 66_band:0 "66"
 68_band:0 "68"
 70_band:0 "70"
 72_band:0 "72"